
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/duongang/Downloads/cmake-3.31.0-windows-x86_64/cmake-3.31.0-windows-x86_64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/duongang/Downloads/cmake-3.31.0-windows-x86_64/cmake-3.31.0-windows-x86_64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
